### ISSUE TITLE
clickover + bootstrap 2.2.0 not working

### ISSUE THREAD

**Issue by Sadrak** [lecar-red/bootstrapx-clickover#21] opened 2012-10-31 07:49 UTC
when you click on a clickover nothing happend and you see a error in the console:

Uncaught TypeError: Cannot read property 'currentTarget' of undefined
Tooltip.toggle
$.extend.clickery
e.extend.proxy.g
f.event.dispatch
f.event.add.h.handle.i

  , toggle: function (e) {
      var self = $(e.currentTarget)[this.type](this._options).data(this.type)
Uncaught TypeError: Cannot read property 'currentTarget' of undefined
      self[self.tip().hasClass('in') ? 'hide' : 'show']()
    }

**Comment by Sadrak** [comment] 2012-10-31 08:09
After using bootstrap-tooltip.js from 2.1.1 all is working again (+ all other files 2.2.0). The diff from 2.1.1 to 2.2.0 is not much for the bootstrap-tooltip.js, but i cannot find the problem.

**Comment by lecar-red** [comment] 2012-10-31 13:58
I'll take a look

**Comment by huyl** [comment] 2012-11-05 09:54
+1

**Comment by greatwalks** [comment] 2012-11-05 21:25
I'm getting this too

**Comment by Yohn** [comment] 2012-11-05 22:51
I recently found a bug with the "toggle" feature within the tooltip, which then break all tooltip('toggle') and popover('toggle') you can find my pull request to correct the problem - twitter/bootstrap#5768
changing the toggle function to the following seems to fix it

``` javascript
toggle: function (e) {
       var self = (e) ? $(e.currentTarget)[this.type](this._options).data(this.type) : this
       self.tip().hasClass('in') ? self.hide() : self.show()
}
```

**Comment by thirtified** [comment] 2012-11-16 16:46
This seems to be indeed caused by a change in the Bootstrap Tooltip API, apparently a rather bad decision over there. However, here is a fix to work around the issue:

Lines 66–67 in `bootstrapx-clickover.js`:

``` javascript
...
    // we could override this to provide show and hide hooks 
    this[ this.isShown() ? 'hide' : 'show' ]();
...
```

**Comment by lecar-red** [comment] 2012-11-20 22:03
should be closed in most recent release

**Closed as completed by lecar-red** 2012-11-20 22:03 UTC

**Comment by huyl** [comment] 2012-11-21 22:50
really?  I applied @thirtified 's patch manually and that didn't work for me.

I guess I'll have to confirm at some point...

**Comment by bensquire** [comment] 2012-12-10 08:56
This error is still causing me issues in TB 2.2.2, added this fix https://github.com/twitter/bootstrap/pull/6176/files and all works fine.

**Comment by atomgiant** [comment] 2012-12-10 16:54
toggle is definitely broken for me in the current 2.2.2 as well.  I can confirm the fix: https://github.com/twitter/bootstrap/pull/6176/files fixes it for me too.
